config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"

  # Defines the root path route ("/")
  root "blog_posts#index"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :blog_posts do
    collection do
      get 'my_blogs'
    end
  end

  get 'feedback', to: 'feedback#new'
  post 'feedback', to: 'feedback#create'

  # API Routes
  namespace :api do
    namespace :v1 do
      resources :blog_posts, only: [:index, :show, :create, :update, :destroy]
    end
  end
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy

  has_rich_text :content
  has_one_attached :image

  validates :title, :content, presence: true

  scope :sorted, -> { order(published_at: :desc, updated_at: :desc) }
  scope :draft, -> { where(published_at: nil) }
  scope :published, -> { where("published_at <= ?", Time.zone.now) }
  scope :scheduled, -> { where("published_at > ?", Time.zone.now) }

  def draft?
    published_at.nil?
  end
  def published?
    published_at? && published_at <= Time.zone.now
  end

  def scheduled?
    published_at? && published_at >= Time.zone.now
  end
end

app/controllers/api/v1/blog_posts_controller.rb
# app/controllers/api/v1/blog_posts_controller.rb
module Api
  module V1
    class BlogPostsController < ApplicationController
      before_action :set_blog_post, only: [:show, :update, :destroy, :like, :unlike]

      # GET /api/v1/blog_posts
      def index
        @blog_posts = BlogPost.all
        render json: @blog_posts
      end

      # GET /api/v1/blog_posts/:id
      def show
        render json: @blog_post
      end

      # POST /api/v1/blog_posts
      def create
        @blog_post = BlogPost.new(blog_post_params)
        if @blog_post.save
          render json: @blog_post, status: :created
        else
          render json: @blog_post.errors, status: :unprocessable_entity
        end
      end

      # PATCH/PUT /api/v1/blog_posts/:id
      def update
        if @blog_post.update(blog_post_params)
          render json: @blog_post
        else
          render json: @blog_post.errors, status: :unprocessable_entity
        end
      end

      # DELETE /api/v1/blog_posts/:id
      def destroy
        @blog_post.destroy
      end

      # POST /api/v1/blog_posts/:id/like
      def like
        @blog_post.increment!(:likes_count)
        render json: { message: 'Liked successfully' }
      end

      # DELETE /api/v1/blog_posts/:id/unlike
      def unlike
        @blog_post.decrement!(:likes_count)
        render json: { message: 'Unliked successfully' }
      end

      private

      def set_blog_post
        @blog_post = BlogPost.find(params[:id])
      end

      def blog_post_params
        params.require(:blog_post).permit(:title, :content)
      end
    end
  end
end

app/controllers/blog_posts_controller.rb
# app/controllers/blog_posts_controller.rb

class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @blog_posts = BlogPost.published.sorted
  end

  def show
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = current_user.blog_posts.build(blog_post_params)

    if params[:save_as_draft]
      @blog_post.published_at = nil
    elsif @blog_post.published_at.blank?
      @blog_post.published_at = Time.zone.now
    end

    if @blog_post.save
      redirect_to @blog_post, notice: 'Blog post was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post, notice: 'Blog post was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog_post.destroy
    redirect_to root_path, notice: 'Blog post was successfully destroyed.'
  end

  def my_blogs
    @blog_posts = current_user.blog_posts
  end

  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :content, :published_at, :image)
  end

  def set_blog_post
    @blog_post = user_signed_in? ? BlogPost.find(params[:id]) : BlogPost.published.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path, alert: 'Blog post not found.'
  end
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/blog_posts/edit.html.erb
<div class="p-6 bg-white rounded-lg shadow-md">
  <h1 class="text-2xl font-bold mb-6">Edit Blog Post</h1>
  <%= render partial: "partials/form", locals: { blog_post: @blog_post } %>
  <%= button_to "Delete", @blog_post, method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "mt-6 inline-block bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded" %>
</div>

app/views/blog_posts/index.html.erb
<section class="py-24">
  <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
    <h2 class="font-manrope text-4xl font-bold text-gray-900 text-center mb-16">Our latest blog</h2>
    <% if user_signed_in? %>
      <div class="mb-8 text-center">
        <%= link_to "New Post", new_blog_post_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full transition duration-300 ease-in-out transform hover:scale-105" %>
      </div>
    <% end %>
    <div class="flex justify-center gap-y-8 lg:gap-y-0 flex-wrap md:flex-wrap lg:flex-nowrap lg:flex-row lg:justify-between lg:gap-x-8">
      <% @blog_posts.each do |blog_post| %>
        <div class="group w-full max-lg:max-w-xl lg:w-1/3 border border-gray-300 rounded-2xl">
          <div class="flex items-center">
            <% if blog_post.image.attached? %>
              <%= image_tag blog_post.image, class: "rounded-t-2xl w-full" %>
            <% else %>
              <img src="https://via.placeholder.com/300x200" alt="Blog image" class="rounded-t-2xl w-full">
            <% end %>
          </div>
          <div class="p-4 lg:p-6 transition-all duration-300 rounded-b-2xl group-hover:bg-gray-50">
            <span class="dark:text-gray-400 font-medium mb-5">@<%= blog_post.user.username %></span>
            <span class="text-indigo-600 font-medium mb-3 block"><%= blog_post.created_at.strftime("%b %d, %Y") %></span>
            <h4 class="text-xl text-gray-900 font-medium leading-8 mb-5"><%= link_to blog_post.title, blog_post, class: "hover:underline" %></h4>
            <%= link_to "Read more..", blog_post, class: "cursor-pointer text-lg text-indigo-600 font-semibold" %>
            <div>
              <% if blog_post.draft? %>
                <span class="inline-block px-2 py-1 rounded bg-yellow-100 text-yellow-700">Draft</span>
              <% elsif blog_post.scheduled? %>
                <span class="inline-block px-2 py-1 rounded bg-blue-100 text-blue-700">Scheduled</span>
              <% elsif blog_post.published? %>
                <span class="inline-block px-2 py-1 rounded bg-green-100 text-green-700">Published</span>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/blog_posts/my_blogs.html.erb
<section class="py-24">
  <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
    <h2 class="font-manrope text-4xl font-bold text-gray-900 text-center mb-16">My Blogs</h2>
    <% if user_signed_in? %>
      <div class="mb-8 text-center">
        <%= link_to "New Post", new_blog_post_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full transition duration-300 ease-in-out transform hover:scale-105" %>
      </div>
    <% end %>
    <div class="flex justify-center gap-y-8 lg:gap-y-0 flex-wrap md:flex-wrap lg:flex-nowrap lg:flex-row lg:justify-between lg:gap-x-8">
      <% @blog_posts.each do |blog_post| %>
        <div class="group w-full max-lg:max-w-xl lg:w-1/3 border border-gray-300 rounded-2xl">
          <div class="flex items-center">
            <% if blog_post.image.attached? %>
              <%= image_tag blog_post.image, class: "rounded-t-2xl w-full" %>
            <% else %>
              <img src="https://via.placeholder.com/300x200" alt="Blog image" class="rounded-t-2xl w-full">
            <% end %>
          </div>
          <div class="p-4 lg:p-6 transition-all duration-300 rounded-b-2xl group-hover:bg-gray-50">
            <span class="text-indigo-600 font-medium mb-3 block"><%= blog_post.created_at.strftime("%b %d, %Y") %></span>
            <h4 class="text-xl text-gray-900 font-medium leading-8 mb-5"><%= link_to blog_post.title, blog_post, class: "hover:underline" %></h4>
            <%= link_to "Read more..", blog_post, class: "cursor-pointer text-lg text-indigo-600 font-semibold" %>
            <div>
              <% if blog_post.draft? %>
                <span class="inline-block px-2 py-1 rounded bg-yellow-100 text-yellow-700">Draft</span>
              <% elsif blog_post.scheduled? %>
                <span class="inline-block px-2 py-1 rounded bg-blue-100 text-blue-700">Scheduled</span>
              <% elsif blog_post.published? %>
                <span class="inline-block px-2 py-1 rounded bg-green-100 text-green-700">Published</span>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/blog_posts/new.html.erb
<div class="p-6 bg-white rounded-lg shadow-md">
  <h1 class="text-2xl font-bold mb-6">New Blog Post</h1>
  <%= render partial: "partials/form", locals: { blog_post: @blog_post } %>
</div>

app/views/blog_posts/show.html.erb
<div class="p-6 bg-white rounded-lg shadow-md">
  <h1 class="text-3xl font-bold text-gray-900 mb-4"><%= @blog_post.title %></h1>
<!--  <div class="text-gray-700 leading-relaxed mb-6">-->
    <%#= @blog_post.content %>
<!--  </div>-->
  <div class="container mx-auto px-4 py-8">
    <div class="bg-white shadow-md rounded-lg p-6 mb-4">
      <p class="text-gray-700 mb-4">
        <strong class="block text-xl font-semibold mb-2">Author:</strong>
        <%#= @blog_post.user.name %>
      </p>
      <p class="text-gray-700 mb-4">
        <strong class="block text-xl font-semibold mb-2">Title:</strong>
        <%= @blog_post.title %>
      </p>
      <p class="text-gray-700">
        <strong class="block text-xl font-semibold mb-2">Content:</strong>
        <%= @blog_post.content %>
      </p>
    </div>
  </div>

  <div class="flex justify-end space-x-4">
    <% if user_signed_in? %>
      <%= link_to "Edit", edit_blog_post_path(@blog_post), class: "inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
    <% end %>
  </div>
</div>