config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"

  # Defines the root path route ("/")
  root "blog_posts#index"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :blog_posts do
    collection do
      get 'my_blogs'
    end
  end

  get 'feedback', to: 'feedback#new'
  post 'feedback', to: 'feedback#create'

  # API Routes
  namespace :api do
    namespace :v1 do
      resources :blog_posts, only: [:index, :show, :create, :update, :destroy]
    end
  end
end

app/views/partials/_form.html.erb
<%= form_with model: blog_post, class: "space-y-6" do |form| %>
  <% if form.object.errors.any? %>
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
      <% form.object.errors.full_messages.each do |message| %>
        <div class="block"><%= message %></div>
      <% end %>
    </div>
  <% end %>

  <div class="space-y-2">
    <%= form.label :title, class: "block text-sm font-medium text-gray-700" %>
    <%= form.text_field :title, class: "mt-1 block w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
  </div>

  <div class="space-y-2">
    <%= form.label :image, "Cover Image", class: "block text-sm font-medium text-gray-700" %>
    <%= form.file_field :image, class: "mt-1 block w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
  </div>

  <div class="space-y-2">
    <%= form.label :content, class: "block text-sm font-medium text-gray-700" %>
    <%= form.rich_text_area :content, class: "mt-1 block w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
  </div>

  <div class="space-y-2">
    <%= form.label :schedule, class: "block text-sm font-medium text-gray-700" %>
    <%= form.check_box :schedule, { id: 'schedule_checkbox' }, 'true', 'false' %>
    <%= form.label :schedule, "Schedule this blog for later", class: "text-sm font-medium text-gray-700" %>
  </div>

  <div id="datetime_select_container" class="space-y-2" style="display: none;">
    <%= form.label :published_at, class: "block text-sm font-medium text-gray-700" %>
    <%= form.datetime_select :published_at, include_blank: true, class: "mt-1 block w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
  </div>

  <%= form.button "Submit", class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
  <%= form.button "Save as Draft", name: 'save_as_draft', class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-gray-600 hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500" %>
<% end %>

app/views/partials/_image_upload.html.erb
<!-- app/views/shared/_image_upload.html.erb -->
<div class="profile-image-upload mb-4 relative">
  <div class="profile-image-placeholder w-32 h-32 bg-gray-200 rounded-full flex items-center justify-center relative cursor-pointer">
    <% if form.object.profile_image.attached? %>
      <%= image_tag form.object.profile_image.variant(resize: "150x150!"), id: 'profile-image', class: 'w-full h-full object-cover rounded-full' %>
    <% else %>
      <img src="https://via.placeholder.com/150" alt="Profile image placeholder" id="profile-image" class="w-full h-full object-cover rounded-full">
    <% end %>
    <input type="file" id="profile_image_input" class="absolute inset-0 opacity-0 cursor-pointer" name="user[profile_image]" accept="image/*">
    <div class="hover-overlay absolute inset-0 bg-black opacity-50 flex items-center justify-center rounded-full hidden">
      <span class="text-white">Choose Profile Image</span>
    </div>
  </div>
</div>

app/views/partials/_navbar.html.erb
<nav class="bg-white border-gray-200 dark:bg-gray-900 py-4">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <a href="/" class="flex items-center space-x-3 rtl:space-x-reverse">
      <img src="https://flowbite.com/docs/images/logo.svg" class="h-8" alt="Flowbite Logo" />
      <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Daily Drift</span>
    </a>
    <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
      <span class="sr-only">Open main menu</span>
      <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
      </svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul class="font-medium flex flex-col items-center p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 rtl:space-x-reverse md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
        <% if user_signed_in? %>
          <li class="flex items-center">
            <%= link_to edit_user_registration_path, class: "flex items-center space-x-2 rtl:space-x-reverse text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent" do %>
              <div class="w-10 h-10 rounded-full overflow-hidden bg-gray-200 mr-1">
                <%= image_tag(current_user.profile_image.attached? ? url_for(current_user.profile_image) : "placeholder.jpg", class: "w-full h-full object-cover") %>
              </div>
              <span>Profile</span>
            <% end %>
          </li>
          <li>
            <%= link_to "My Blogs", my_blogs_blog_posts_path, class: "block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent" %>
          </li>
          <li>
            <%= link_to "Feedback", feedback_path, class: "block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent" %>
          </li>
          <li>
            <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent" %>
          </li>
        <% else %>
          <li>
            <%= link_to "Login", new_user_session_path, class: "block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent" %>
          </li>
          <li>
            <%= link_to "Register", new_user_registration_path, class: "block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>